import { test, expect } from '@playwright/test';
import path from 'path';
import * as stepGroups from '../../../src/helpers/step-groups';

test.describe('REG_Bid Maps', () => {
  let vars: Record<string, string> = {};

  test.beforeEach(async () => {
    vars = {};
  });

  test('REG_TS01_TC04_Verify that if user selects two companies \\\"A and B\\\" and if company a has both exe type and company b has only chase exe type, then user should be able to view only chase exe type in th', async ({ page }) => {
    const testData: Record<string, string> = {}; // TODO: Load from test data profile

    await stepGroups.stepGroup_Login_to_CORR_Portal(page, vars);
    await page.locator("//span[contains(@class,'circle')]").waitFor({ state: 'hidden' });
    // [DISABLED] Navigation to Customer Permission
    // await stepGroups.stepGroup_Navigation_to_Customer_Permission(page, vars);
    await stepGroups.stepGroup_Navigate_to_Customer_Permission_to_Fetch_First_Company_Name(page, vars);
    await stepGroups.stepGroup_Store_Company_Names_from_Company_Permissions(page, vars);
    await stepGroups.stepGroup_Store_More_Company_Name(page, vars);
    await stepGroups.stepGroup_Standard_and_Chase_Direct_ON_for_Company(page, vars);
    await stepGroups.stepGroup_Store_More_Company_Name(page, vars);
    await stepGroups.stepGroup_Only_Chase_Direct_On_for_Company(page, vars);
    await page.locator("//span[text()[normalize-space() = \"Administration\"]]").click();
    await page.locator("//span[text()[normalize-space() = \"Bid Maps\"]]").click();
    await page.locator("//span[contains(@class,'circle')]").waitFor({ state: 'hidden' });
    await page.locator("//button[text()[normalize-space() = \"Add New Mapping\"]]").click();
    await expect(page.locator("//h5[text()[normalize-space() = \"Create New Map\"]]")).toBeVisible();
    vars["Create New Map"] = new Date().toLocaleDateString('en-US') /* format: dd/MM/yyyy/HH:mm:ss */;
    vars["Create New Map"] = "Testsigma_" + vars["Create New Map"];
    await page.locator("mapName").fill(vars["Create New Map"]);
    vars["BidMap"] = await page.locator("mapName").inputValue() || '';
    await page.locator("//button[@aria-label=\"Create\"]").click();
    await page.locator("//span[contains(@class,'circle')]").waitFor({ state: 'hidden' });
    await expect(page.locator("//span[contains(.,' $|Create New Map|')]")).toContainText(vars["Create New Map"]);
    await page.locator("//div//div[@id=\"companySelect\"]//div//button[@id=\"multiSelectDropDown\"]").click();
    await stepGroups.stepGroup_Enter_Company_Name_in_New_Map_Filter(page, vars);
    await stepGroups.stepGroup_Enter_Company_Name_in_New_Map_Filter(page, vars);
    await expect(page.locator("//span[@class=\"counter bg-white text-primary mx-2 text-center fw-semibold small\"]")).toContainText("2");
    await page.locator("//button[contains(text(),\" Apply Selected \")]").click();
    vars["CompanyNamePartial"] = String(vars["FirstCompanyName"]).substring(0, String(vars["FirstCompanyName"]).length - 4);
    await expect(page.locator("//div[contains(@class,'pill rounded-pill')]//span[contains(text(),'$|CompanyNamePartial|')]")).toContainText(vars["FirstCompanyName"]);
    vars["CompanyNamePartial"] = String(vars["SecondCompanyName"]).substring(0, String(vars["SecondCompanyName"]).length - 10);
    await expect(page.locator("//div[contains(@class,'pill rounded-pill')]//span[contains(text(),'$|CompanyNamePartial|')]")).toContainText(vars["SecondCompanyName"]);
    await page.locator("//select[@aria-label=\"Dropdown selection\"]").click();
    await expect(page.locator("//select[@aria-label=\"Dropdown selection\"]")).toHaveValue("STANDARD");
    await page.locator("(//*[contains(@aria-label,\"Remove\")]//i[contains(@class , 'fas fa-times-circle text-primary')])[2]").click();
    await page.locator("//div[text()[normalize-space() = \"Selected (1)\"]]").click();
    await page.locator("//input[@placeholder=\"Search\"]").fill(vars["SecondCompanyName"]);
    await expect(page.locator("(//input[@type=\"checkbox\"])[1]")).toBeVisible();
    await page.locator("//div[text()[normalize-space() = \"Selected (1)\"]]").click();
    await page.locator("(//*[contains(@aria-label,\"Remove\")]//i[contains(@class , 'fas fa-times-circle text-primary')])[1]").click();
    await page.locator("//div//div[@id=\"companySelect\"]//div//button[@id=\"multiSelectDropDown\"]").click();
    await stepGroups.stepGroup_Enter_Company_Name_in_New_Map_Filter(page, vars);
    await stepGroups.stepGroup_Enter_Company_Name_in_New_Map_Filter(page, vars);
    await page.locator("//button[contains(text(),\" Apply Selected \")]").click();
    await page.locator("//select[@aria-label=\"Dropdown selection\"]").click();
    await expect(page.locator("//select[@aria-label=\"Dropdown selection\"]").locator('option', { hasText: "CHASE_DIRECT" })).toBeVisible();
    await page.locator("//i[@class=\"fas fa-times-circle text-primary\"]").click();
    await page.locator("//i[@class=\"fas fa-times-circle text-primary\"]").click();
    await page.locator("//div//div[@id=\"companySelect\"]//div//button[@id=\"multiSelectDropDown\"]").click();
    await stepGroups.stepGroup_Enter_Company_Name_in_New_Map_Filter(page, vars);
    await expect(page.locator("//button[contains(text(),\" Apply Selected \")]")).toContainText("1");
    await page.locator("//button[contains(text(),\" Apply Selected \")]").click();
    await page.locator("//select[@aria-label=\"Dropdown selection\"]").click();
    await page.locator("//select[@aria-label=\"Dropdown selection\"]").hover();
    await page.locator("//select[@aria-label=\"Dropdown selection\"]").click();
    await page.locator("//select[@aria-label=\"Dropdown selection\"]").hover();
    await page.locator("//select[@aria-label=\"Dropdown selection\"]").selectOption({ label: testData["Execution Type"] });
    await expect(page.locator("//select[@aria-label=\"Dropdown selection\"]")).toHaveValue(testData["Execution Type"]);
    await page.locator("//i[@class=\"fas fa-times-circle text-primary\"]").click();
    await page.locator("//div//div[@id=\"companySelect\"]//div//button[@id=\"multiSelectDropDown\"]").click();
    await stepGroups.stepGroup_Enter_Company_Name_in_New_Map_Filter(page, vars);
    await stepGroups.stepGroup_Enter_Company_Name_in_New_Map_Filter(page, vars);
    await page.locator("//input[@placeholder=\"Search\"]").clear();
    await page.locator("(//input[@type=\"checkbox\"])[4]").check();
    vars["ThirdCompanyName"] = await page.locator("(//input[@type=\"checkbox\"])[4]//following-sibling::div/span").textContent() || '';
    await page.locator("(//input[@type=\"checkbox\"])[5]").check();
    vars["FourthCompanyName"] = await page.locator("(//input[@type=\"checkbox\"])[5]//following-sibling::div/span").textContent() || '';
    await page.locator("(//input[@type=\"checkbox\"])[6]").check();
    vars["FifthCompanyName"] = await page.locator("(//input[@type=\"checkbox\"])[6]//following-sibling::div/span").textContent() || '';
    await page.locator("(//input[@type=\"checkbox\"])[7]").check();
    vars["SixthCompanyName"] = await page.locator("(//input[@type=\"checkbox\"])[7]//following-sibling::div/span").textContent() || '';
    await expect(page.locator("//button[contains(text(),\" Apply Selected \")]")).toContainText("6");
    await page.locator("//button[contains(text(),\" Apply Selected \")]").click();
    vars["ExpectedThirdCompanyName"] = await page.locator("(//div[@role=\"listitem\"])[2]").textContent() || '';
    expect(String(vars["ExpectedThirdCompanyName"])).toBe(vars["ThirdCompanyName"]);
    await expect(page.locator("(//div[@role=\"listitem\"])[3]")).toContainText(vars["FourthCompanyName"]);
    vars["ExpectedFifthCompanyName"] = String(vars["FifthCompanyName"]).trim();
    vars["FifthCompanyName1"] = await page.locator("(//div[@role=\"listitem\"])[4]").textContent() || '';
    vars["FifthCompanyName1"] = String(vars["FifthCompanyName1"]).trim();
    expect(String(vars["FifthCompanyName1"])).toBe(vars["ExpectedFifthCompanyName"]);
    await page.locator("//span[text()[normalize-space() = \"+2 more\"]]").click();
    vars["lastcompany"] = await page.locator("(//td[@data-title=\"Company\"])[5]").textContent() || '';
    expect(String(vars["lastcompany"])).toBe(vars["SixthCompanyName"]);
    await page.locator("//button[@class=\"btn bg-transparent border-0 m-0\"]").click();
    await page.waitForLoadState('networkidle');
    // [DISABLED] Verify that the current page does not displays text FirstCompanyName
    // await expect(page.getByText(vars["FirstCompanyName"])).not.toBeVisible();
    await expect(page.getByText(vars["SecondCompanyName"])).not.toBeVisible();
    await expect(page.locator("//button/span[text()='+2 more']")).toContainText("2");
    await page.locator("//button/span[text()='+2 more']").hover();
    await expect(page.locator("//select[@aria-label=\"Dropdown selection\"]")).toHaveValue('');
    await page.locator("//span[text()[normalize-space() = \"+1 more\"]]").click();
    await page.waitForLoadState('networkidle');
    vars["Added On"] = new Date().toLocaleDateString('en-US') /* format: MM/dd/yyyy hh:mm a */;
    vars["Added On Bid Map"] = await page.locator("(//td[@data-title=\"Added On\"])[1]").textContent() || '';
    expect(String(vars["Added On"])).toBe(vars["Added On Bid Map"]);
    await page.locator("//i[contains(@class, 'fa-lg') and contains(@class, 'color-primary') and contains(@class, 'fa-times')]").click();
    await page.waitForLoadState('networkidle');
    await page.locator("//div[contains(@class, 'container') and contains(@class, 'd-flex')]/div[2]/button[2]").click();
    await page.locator("//span[contains(@class,'circle')]").waitFor({ state: 'hidden' });
    await expect(page.locator("//input[contains(@id,\"mappingName\")]")).toBeEditable();
    await page.locator("//input[contains(@id,\"mappingName\")]").fill(Array.from({length: 5}, () => "ab".charAt(Math.floor(Math.random() * 2))).join(''));
    vars["EditedFileName"] = await page.locator("//input[contains(@id,\"mappingName\")]").inputValue() || '';
    await expect(page.locator("//input[contains(@id,\"mappingName\")]")).toHaveValue(vars["EditedFileName"]);
    await page.locator("(//button[contains(.,'Save Draft & Exit')])[1]").click();
    await page.locator("//span[contains(@class,'circle')]").waitFor({ state: 'hidden' });
    await expect(page.getByText(vars["EditedFileName"])).toBeVisible();
  });
});
