import { test, expect } from '@playwright/test';
import path from 'path';
import * as stepGroups from '../../../src/helpers/step-groups';

test.describe('REG_Bid Maps', () => {
  let vars: Record<string, string> = {};

  test.beforeEach(async () => {
    vars = {};
  });

  test('REG_TS11_TC03_Verify that the user can Edit and Delete a rule.', async ({ page }) => {
    // Prerequisite: REG_TS11_TC01_Verify that the user can Create and Duplicate rule.
    // TODO: Ensure prerequisite test passes first

    const testData: Record<string, string> = {}; // TODO: Load from test data profile

    await page.waitForLoadState('networkidle');
    await page.locator("//button[contains(text(),\"$|BidMap|\")]").click();
    await page.locator("//span[contains(@class,'circle')]").waitFor({ state: 'hidden' });
    await expect(page.locator("//span[text()[normalize-space() = \"Map Headers\"]]")).toBeVisible();
    await page.locator("//span[text()[normalize-space() = \"Map Headers\"]]").click();
    await page.locator("//span[contains(@class,'circle')]").waitFor({ state: 'hidden' });
    await expect(page.locator("//span[text()='Enumeration Mapping']")).toBeVisible();
    await page.locator("//span[text()='Enumeration Mapping']").click();
    await expect(page.locator("//h5[text()[normalize-space() = \"Save and Move to Next Page\"]]")).toBeVisible();
    await page.locator("(//button[@type=\"button\"])[last()]").click();
    await page.locator("//span[contains(@class,'circle')]").waitFor({ state: 'hidden' });
    await expect(page.locator("//span[text()[normalize-space() = \"Rules and Actions\"]]")).toBeVisible();
    await page.locator("//span[text()[normalize-space() = \"Rules and Actions\"]]").click();
    await expect(page.locator("//h5[text()[normalize-space() = \"Save and Move to Next Page\"]]")).toBeVisible();
    await page.locator("(//button[@type=\"button\"])[last()]").click();
    await page.locator("//span[contains(@class,'circle')]").waitFor({ state: 'hidden' });
    await expect(page.locator("//span[text()[normalize-space() = \"Save and Publish\"]]")).toBeVisible();
    await expect(page.locator("//h6[text()[normalize-space() = \"Add Conditions\"]]")).toBeVisible();
    vars["Rule Name"] = await page.locator("//input[@placeholder=\"Enter a Rule Name\"]").inputValue() || '';
    await page.locator("//input[@placeholder=\"Enter a Rule Name\"]").fill(Array.from({length: 2}, () => "ab".charAt(Math.floor(Math.random() * 2))).join(''));
    vars["UpdatedRuleName"] = await page.locator("//input[@placeholder=\"Enter a Rule Name\"]").inputValue() || '';
    expect(String(vars["Rule Name"])).toBe(vars["UpdatedRuleName"]);
    await page.locator("//div[text()[normalize-space() = \"Selected (1)\"]]").click();
    await page.locator("(//span[text()=\"Ineligible\"]/../..//input[@type=\"checkbox\"])[1]").check();
    await page.locator("//*[contains(text(),\" Apply Selected\")]").click();
    await expect(page.locator("//div[contains(text(),\"Selected (2)\")]")).toBeVisible();
    await page.locator("//div[contains(text(),\"Selected (2)\")]").click();
    await expect(page.locator("(//span[text()=\"Products\"]/../..//input[@type=\"checkbox\"])")).toBeVisible();
    await expect(page.locator("(//span[text()=\"Ineligible\"]/../..//input[@type=\"checkbox\"])[1]")).toBeVisible();
    await page.locator("//*[contains(text(),\" Apply Selected\")]").click();
    vars["BeforeWhenBidField1"] = await page.locator("(//label[text()=\" When Bid Field \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[1]").inputValue() || '';
    vars["BeforeOperator1"] = await page.locator("//label[text()=\" When Bid Field \"]/../..//select").inputValue() || '';
    vars["BeforeBidEnumTapeValue1"] = await page.locator("(//label[text()=\" Bid Enumerated Tape Value \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[1]").inputValue() || '';
    vars["BeforeActionChaseFieldName1"] = await page.locator("(//*[text()=\"Chase Field Name\"]/..//select)[1]").evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    vars["BeforeActionChaseValue1"] = await page.locator("(//*[text()=\"Chase Value\"]/..//select)[1]").evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    await page.locator("(//label[text()=\" When Bid Field \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[1]").click();
    await page.locator("//input[@aria-label=\"Search options\"]").fill(testData["UpdatedWhenBidFieldName"]);
    await page.locator("//div[contains(@class, 'shadow') and contains(@class, 'dropdown-menu') and contains(@class, 'show')]//button[@role=\"option\"]//span[@title=\"Correspondent Loan Number\"]").click();
    await expect(page.locator("(//label[text()=\" When Bid Field \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[1]")).toContainText(testData["UpdatedWhenBidFieldName"]);
    await page.locator("//label[text()=\" When Bid Field \"]/../..//select").selectOption({ label: testData["Operator"] });
    await expect(page.locator("//label[text()=\" When Bid Field \"]/../..//select")).toHaveValue(testData["Operator"]);
    await page.locator("(//label[text()=\" Bid Enumerated Tape Value \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[1]").click();
    await page.locator("//span[@title=\"SAIKAT_18_FEB_002\"]").click();
    await expect(page.locator("(//label[text()=\" Bid Enumerated Tape Value \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[1]")).toContainText(testData["UpdatedBidEnumeratedTapeValue"]);
    vars["ActionChaseFiledNew1"] = await page.locator("(//label[text()=\"Chase Field Name\"]/.././/select/..//option)[5]").textContent() || '';
    await page.locator("(//*[text()=\"Chase Field Name\"]/..//select)[1]").selectOption({ index: parseInt("4") });
    await expect(page.locator("(//*[text()=\"Chase Field Name\"]/..//select)[1]")).toContainText(vars["ActionChaseFiledNew1"]);
    vars["ActionChaseValueNameNew1"] = await page.locator("(//label[text()=\"Chase Value\"]/.././/select/..//option)[3]").textContent() || '';
    await page.locator("(//*[text()=\"Chase Value\"]/..//select)[1]").selectOption({ index: parseInt("2") });
    await expect(page.locator("(//*[text()=\"Chase Value\"]/..//select)[1]")).toContainText(vars["ActionChaseValueNameNew1"]);
    vars["AfterWhenBidField1"] = await page.locator("(//label[text()=\" When Bid Field \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[1]").inputValue() || '';
    vars["AfterOperator1"] = await page.locator("//label[text()=\" When Bid Field \"]/../..//select").inputValue() || '';
    vars["AfterBidEnurmeratedTapeValue1"] = await page.locator("(//label[text()=\" Bid Enumerated Tape Value \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[1]").inputValue() || '';
    vars["AfterActionChaseFieldName1"] = await page.locator("(//*[text()=\"Chase Field Name\"]/..//select)[1]").evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    vars["AfterActionChaseValue1"] = await page.locator("(//*[text()=\"Chase Value\"]/..//select)[1]").evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    expect(String(vars["BeforeWhenBidField1"])).toBe(vars["AfterWhenBidField1"]);
    expect(String(vars["BeforeOperator1"])).toBe(vars["AfterOperator1"]);
    expect(String(vars["BeforeBidEnumTapeValue1"])).toBe(vars["AfterBidEnurmeratedTapeValue1"]);
    expect(String(vars["BeforeActionChaseFieldName1"])).toBe(vars["AfterActionChaseFieldName1"]);
    expect(String(vars["BeforeActionChaseValue1"])).toBe(vars["AfterActionChaseValue1"]);
    await page.locator("(//button[@class=\"btn bg-transparent text-primary\"])[2]").click();
    await page.locator("(//label[text()=\" When Bid Field \"]/../../../..//div[contains(@class,\"flex-grow-1 text-start\")])[5]").click();
    await page.locator("(//input[@aria-label=\"Search options\"])[5]").fill(testData["WhenBidFieldValue-3"]);
    await page.locator("//div[contains(@class, 'shadow') and contains(@class, 'dropdown-menu') and contains(@class, 'show')]//button[@role=\"option\"]//span[@title=\"Appraised Value\"]").click();
    await page.locator("(//label[text()=\" When Bid Field \"]/../../../..//select)[3]").selectOption({ label: testData["Operator 3"] });
    await page.locator("(//label[text()=\" Bid Enumerated Tape Value \"]/../../../../../..//div[contains(@class,\"flex-grow-1 text-start\")])[6]").click();
    await page.locator("//span[@title=\"425000\"]").click();
    await expect(page.locator("(//label[text()=\" When Bid Field \"]/../../../..//div[contains(@class,\"flex-grow-1 text-start\")])[5]")).toContainText(testData["WhenBidFieldValue-3"]);
    await expect(page.locator("(//label[text()=\" When Bid Field \"]/../../../..//select)[3]")).toHaveValue(testData["Operator 3"]);
    await expect(page.locator("(//label[text()=\" Bid Enumerated Tape Value \"]/../../../../../..//div[contains(@class,\"flex-grow-1 text-start\")])[6]")).toContainText(testData["BidEnumeraedTapeValue - 3"]);
    await page.locator("//span[contains(@class,'circle')]").waitFor({ state: 'hidden' });
    await page.locator("(//button[@class=\"btn bg-transparent text-primary\"])[3]").click();
    await page.locator("(//label[text()=\" When Bid Field \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[2]").click();
    await page.locator("(//input[@aria-label=\"Search options\"])[7]").fill(testData["WhenBidFieldName - Block 2"]);
    await page.locator("//div[contains(@class, 'shadow') and contains(@class, 'dropdown-menu') and contains(@class, 'show')]//button[@role=\"option\"]//span[@title=\"Amortization Type\"]").click();
    await expect(page.locator("(//label[text()=\" When Bid Field \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[2]")).toContainText(testData["WhenBidFieldName - Block 2"]);
    await page.locator("(//label[text()=\" When Bid Field \"]/../../../..//select)[4]").selectOption({ label: testData["Operator - Block 2"] });
    await expect(page.locator("(//label[text()=\" When Bid Field \"]/../../../..//select)[4]")).toHaveValue(testData["Operator - Block 2"]);
    await page.locator("(//label[text()=\" Bid Enumerated Tape Value \"]/../../../../../..//div[contains(@class,\"flex-grow-1 text-start\")])[8]").click();
    await page.locator("//span[@title=\"Fixed\"]").click();
    await expect(page.locator("(//label[text()=\" Bid Enumerated Tape Value \"]/../../../../../..//div[contains(@class,\"flex-grow-1 text-start\")])[8]")).toContainText(testData["BidEnumeratedTapeValue - Block 2"]);
    await page.locator("(//span[text()[normalize-space() = \"Duplicate/Copy\"]])[1]").click();
    await page.locator("(//input[@placeholder=\"Enter a Rule Name\"])[last()]").fill(Array.from({length: 1}, () => "a".charAt(Math.floor(Math.random() * 1))).join(''));
    vars["Updated Rules and Actions name"] = await page.locator("(//input[@placeholder=\"Enter a Rule Name\"])[last()]").inputValue() || '';
    await page.locator("(//span[text()[normalize-space() = \"Delete Rule\"]])[2]").click();
    await expect(page.locator("//h5[text()[normalize-space() = \"Delete Rule\"]]")).toBeVisible();
    await page.locator("(//button[@type=\"button\"])[last()]").click();
    await page.getByText(vars["Updated Rules and Actions name"]).waitFor({ state: 'hidden' });
    await expect(page.getByText(vars["Updated Rules and Actions name"])).not.toBeVisible();
    await page.waitForLoadState('networkidle');
    await page.locator("(//label[text()=\" When Bid Field \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[1]").click();
    vars["Field"] = await page.locator("(//label[text()=\" When Bid Field \"]/..//div[contains(@class,\"flex-grow-1 text-start\")]/../../../..//span)[6]").textContent() || '';
    await page.locator("//input[@aria-label=\"Search options\"]").fill(vars["Field"]);
    await page.locator("//a[@aria-label=\"Select text option\"]").click();
    await expect(page.locator("(//label[text()=\" When Bid Field \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[1]")).toContainText(vars["Field"]);
    await page.locator("(//label[text()=\" Bid Enumerated Tape Value \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[1]").click();
    vars["UpdatedTapevalueField"] = await page.locator("((//label[text()=\" Bid Enumerated Tape Value \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])/../../../..//span)[2]").textContent() || '';
    await page.locator("(//input[@placeholder=\"Search\"])[3]").fill(vars["UpdatedTapevalueField"]);
    await page.locator("//a[@aria-label=\"Select text option\"]").click();
    await expect(page.locator("(//label[text()=\" Bid Enumerated Tape Value \"]/..//div[contains(@class,\"flex-grow-1 text-start\")])[1]")).toContainText(vars["UpdatedTapevalueField"]);
    await page.locator("(//*[text()=\"Chase Field Name\"]/..//select)[1]").click();
    vars["ChaseFieldName"] = await page.locator("((//*[text()=\"Chase Field Name\"]/..//select)[1]/../..//option)[5]").textContent() || '';
    vars["ChaseFieldName"] = String(vars["ChaseFieldName"]).trim();
    await page.locator("(//*[text()=\"Chase Field Name\"]/..//select)[1]").selectOption({ index: parseInt("4") });
    await expect(page.locator("(//*[text()=\"Chase Field Name\"]/..//select)[1]")).toContainText(vars["ChaseFieldName"]);
    vars["ChaseValue"] = await page.locator("((//*[text()=\"Chase Value\"]/..//select)[1]/../..//option)[2]").textContent() || '';
    vars["ChaseValue"] = String(vars["ChaseValue"]).trim();
    await page.locator("(//*[text()=\"Chase Value\"]/..//select)[1]").selectOption({ index: parseInt("1") });
    await expect(page.locator("(//*[text()=\"Chase Value\"]/..//select)[1]")).toContainText(vars["ChaseValue"]);
    await stepGroups.stepGroup_Add_Actions_In_Rules_and_Actions(page, vars);
    await expect(page.locator("//span[text()[normalize-space() = \"Save and Publish\"]]")).toBeVisible();
    await page.locator("//span[text()[normalize-space() = \"Save and Publish\"]]").click();
    await page.locator("//span[contains(@class,'circle')]").waitFor({ state: 'hidden' });
    await expect(page.locator("(//td[@data-title=\"Status\"])[1]")).toContainText("ACTIVE");
    vars["Version"] = await page.locator("(//td[@data-title=\"Version\"])[1]").textContent() || '';
    await expect(page.getByText(vars["Version"])).toBeVisible();
  });
});
